name: dart_web_toolkit
version: 0.2.0+m3
description: >
  Dart Web Toolkit (DWT) is a development toolkit for building and optimizing complex browser-based applications.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://www.dartwebtoolkit.com
dependencies:
  browser: any